name: release

on:
  pull_request:
    branches: 
      - release
    types:
      - opened

permissions:
  pull-requests: write
  contents: write

env:
  ZIP_FILE:   gal_kintetsu.zip
  PR_URL:     ${{ github.event.pull_request.html_url }}
  TAG:        ${{ github.event.pull_request.title }}
  NOTES:      ${{ github.event.pull_request.body }}
  WORK_DIR:   ./_WORK/
  NOTE_FILE:  notes.txt

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create work directory
        run: |
          mkdir -p ${{ env.WORK_DIR }}
        
      - name: Approve and merge PR
        run: |
          gh pr review ${{ env.PR_URL }} --approve
          gh pr merge ${{ env.PR_URL }} --merge --auto
        
      - name: Write update in readme.md
        run: | 
          printf "###${{ env.TAG }}\n${{ env.NOTES }}\n" > ${{ env.WORK_DIR }}${{ env.NOTE_FILE }}
          sed -i -e '/<!-- updateHistory -->/r ${{ env.WORK_DIR }}${{ env.NOTE_FILE }}' readme.md
    
      - name: Commit readme.md
        run: |
          git config user.name  "actions-user"
          git config user.email "65916846+actions-user@users.noreply.github.com"
          git add -u
          git commit -m "${{ env.TAG }}のreadme.mdを作成"
          git push

      - name: Merge into dev and main branches
        run: |
          git checkout dev
          git merge release -m ${{ env.TAG }}の取り込み
          git checkout main
          git merge release -m ${{ env.TAG }}の取り込み