name: release

on:
  push:
    tags:
      - 'v*'
env:
  ZIP_FILE: gal_hankyu.zip

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y simutrans-makeobj

      - name: Checkout
        uses: actions/checkout@master
      
      - name: Make Release Directory
        run: mkdir -p ./release
        
      - name: Run Makeobj
        run: |
          cd ./vehicle
          for dir in `find * -maxdepth 0 -type d`; do
            if [ $dir = "7200" ]; then
              makeobj pak128 ../release/vehicle.Gal_nose$dir.pak ./$dir/*.dat
            else
              makeobj pak128 ../release/vehicle.Gal_hankyu$dir.pak ./$dir/*.dat
            fi
          done 

      - name: Archive Release
        run: |
          if [ -d ./compat_archive/${{ github.ref_name }} ]; then
            cp ./compat_archive/${{ github.ref_name }}/* ./release
            fi
          zip -r -j ${{ env.ZIP_FILE }} ./release
        
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.ZIP_FILE }}"
          bodyFile: "release.md"
          token: ${{ secrets.GITHUB_TOKEN }}